server {
  listen 127.0.0.1:5201;
  server_name localhost;

  root /opt/short_videos-main;
  index index.php index.html;
  client_max_body_size 35m;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_pass 127.0.0.1:9074;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $document_root;
    fastcgi_param DOUYIN_BRIDGE_URL http://127.0.0.1:1314;
    fastcgi_read_timeout 75s;
    fastcgi_send_timeout 75s;
    fastcgi_connect_timeout 15s;
  }

  location ~ /\. {
    deny all;
  }
}
